
# Config for the Admin Chat
# To receive the messages you have to be Op or have the permission minitools.admin_chat.receive
admin_chat:
  chat_prefix: '!' # !message
  chat_send_permission: minitools.admin_chat.sendprefix # Permission required to use the chat_prefix
  message_prefix: '&8[&4Admin&8] &7%player%&8: &7'
  message_suffix: ''

day-message:
  enabled: true
  delay: 86400 # 1 day (in seconds, min 1 but not recommended)
  message: '&6Bonjour, nous sommes le %date%'
  message-on-disable: '&6Au revoir, nous sommes le %date%'
  date-format: 'yyyy-MM-dd HH:mm:ss'

menu:
  enabled: true
  title: 'MiniTools Menu'
  size: 27
  items:
    0:
      item:
        material: CHEST
        display_name: '§rInventaire'
      action: INVENTORY
    1:
      item:
        material: PLAYER_HEAD
        display_name: '§rMenu joueur'
      action: PLAYER

player_menu:
  actions: # Actions available in the player menu
    - GRAVITY
    - FLYING
    - ALLOW_FLIGHT
    - VANISH
    - HIDDEN
    - HIDDEN_PERMANENT
    - SLEEPING_IGNORED
    - DISPLAY_NAME
    - INVULNERABLE
    - GLOWING
    - SILENT
